name: Publish
on:
  push:
    tags: ["v*"]

jobs:
  publish:
    uses: eps-ai-solutions/.github/.github/workflows/npm-publish.yml@main
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      package-name: TEMPLATE_PACKAGE_NAME
    secrets: inherit
